package janjimenezdavidjunquero.treballfinal.mobileapps.tecnocampus.cat.treballfinal.persistance;

import java.util.ArrayList;
import java.util.Arrays;

import janjimenezdavidjunquero.treballfinal.mobileapps.tecnocampus.cat.treballfinal.domain.Pas;
import janjimenezdavidjunquero.treballfinal.mobileapps.tecnocampus.cat.treballfinal.domain.Recepta;

public class ReceptaBBDD {
    private ArrayList<Recepta> data = new ArrayList<>(); // simulació base de dades

    private static ReceptaBBDD instance = null;
    protected ReceptaBBDD() {
        initData();
    }
    public static ReceptaBBDD getInstance() {
        if(instance == null) {
            instance = new ReceptaBBDD();
        }
        return instance;
    }

    public void initData(){
        data.add(new Recepta("GALLETAS SABLÉ DE CHOCOLATE",
                "Cómo hacer galletas de chocolate. Una receta muy dulce. La palabra sablé quiere decir arenado en francés, y esa es la mejor forma de describir a este tipo de galletas. Se trata de una masa frágil y muy crujiente que se desmenuza fácilmente en arenas o migas.", 4.5, "http://www.umami-madrid.com/wp-content/uploads/sable-chocolat-fleur-sel.jpg",
                new ArrayList<Pas>(Arrays.asList(new Pas(1, "En un bol mezclamos los ingredientes secos, la harina, el bicarbonato, la sal y el cacao en polvo. Reservamos.", 3, "IayS_aFue9E"), new Pas(2, "En otro bol batimos la mantequilla con el azúcar hasta formar una crema. La mantequilla debe estar blanda", 1, 1), new Pas(3, "Combinamos ambas mezclas, la de los sólidos y la de la mantequilla en el mismo bol y añadimos el chocolate que habremos troceado o rallado. Mezclamos bien hasta que este compacto y se pueda formar una bola", 5), new Pas(4, "Colocamos la masa sobre un papel de plástico transparente y le damos forma de rulo con las manos.Podemos hacer uno o varios rulos. Envolvemos con el papel de plásticos y los giramos sobre si mismo hasta que nos quede como un caramelo alargado.", 4), new Pas(5, "Guardamos la masa así empaquetada en el frigo durante unas horas, hasta que se haya endurecido totalmente. Retiramos la masa del frigo y con un cuchillo cortamos discos de masa que vamos colocando sobre un papel sulfurizado en una bandeja de horno. El grosor de estos discos debe de ser en torno al medio centímetro. Colocamos las galletas separadas en la bandeja", 60, 60), new Pas(6, "Horneamos con el horno previamente caliente a 180º C", 11, 11), new Pas(7, "Retiramos la bandeja del horno y pasamos las galletas sablé a una rejilla con mucho cuidado ya que estarán aun blanditas hasta que se enfríen totalmente.", 10, 10))),
                new ArrayList<String>(Arrays.asList("140 gr. harina de trigo", "25 gr. cacao en polvo sin azúcar", "120 gr. mantequilla", "130 gr. azúcar", "110 gr. chocolate 70% cacao", "½ cdita. bicarbonato", "¼ cdita. sal (mejor en escamas)", "½ cdita. extracto vainilla"))));


        data.add(new Recepta("MUFFINS DE ARÁNDANOS",
                "Cómo hacer muffins de arándanos. Los muffins, la versión americana de nuestras tradicionales magdalenas, al igual que estas, nos permiten un sinfín de sabores y rellenos. Pero de entre todas, una de las opciones para preparar muffins y asegurarnos el éxito, es incluyendo en su preparación algo de fruta, como los arándanos. Les dará jugosidad y esponjosidad adicional a este dulce, aumentando su sabor y mejorando su textura.", 3, "https://www.recetassinlactosa.com/wp-content/uploads/2017/12/Muffins-de-ar%C3%A1ndanos.jpg",
                new ArrayList<Pas>(Arrays.asList(new Pas(1, "En un bol mezclamos los ingredientes secos menos el azúcar y los arándanos. Tamizamos la harina, la levadura, el bicarbonato y la sal y reservamos..", 4), new Pas(2, "En otro bol grande batimos el huevo con 100 g. de azúcar reservando el resto del azúcar para hacer el relleno de crema de queso. Batimos bien hasta que la mezcla espume. Añadimos el extracto de vainilla, el aceite de girasol, el yogur y seguimos batiendo.", 5), new Pas(3, "Incorporamos 125 gr. de crema de queso y la incorporamos con el resto de ingredientes. Cuando la mezcla esté lista incluimos los arándanos. Vamos agregando la harina e integrando con una espátula sin batir la mezcla en exceso. Sólo lo necesario para que se integre la masa. Reservamos.", 5), new Pas(4, "Preparamos la mezcla de queso mezclando el queso en crema con los 40 gr. de azúcar restantes. Colocamos las cápsulas de papel en un molde para muffins y rellenamos cada una hasta casi la mitad de la altura.", 6), new Pas(5, "Añadimos 1 cucharadita de crema de queso. Tapamos con el resto de la masa hasta rellenar la cápsula unos ¾ de su altura. Espolvoreamos con azúcar.", 3), new Pas(6, "Horneamos, con el horno previamente caliente a 180º C, con calor arriba y abajo", 23, 23))),
                new ArrayList<String>(Arrays.asList("250 gr. harina", "140 gr. azúcar", "1 cdita. levadura química", "1 cdita. bicarbonato sódico", "¼ cdita. sal", "125 gr. yogur natural", "70 ml. aceite de girasol", "1 huevo", "½ cdita. extracto de vainilla", "100 gr. arándanos frescos", "225 gr. crema de queso"))));

        data.add(new Recepta("CARACOLAS DULCES",
                "Hoy os traigo la receta de unas caracolas dulces que, estoy totalmente seguro de que os engancharán. El resultado es un bocado dulce esponjoso, con una masa súper aromática y con mucho sabor.", 3.5, "http://2.bp.blogspot.com/--uCBd6RYDlw/ULI7XozVeoI/AAAAAAAAANM/rpUZO5smVRY/s1600/Caracolas+-+25.11.12.JPG",
                new ArrayList<Pas>(Arrays.asList(new Pas(1, "En un bol mezclamos todos los ingredientes y trabajamos la masa con maquina", 9, 9), new Pas(2, "Ponemos la masa en un bol enharinado y lo tapamos con papel transparente. Dejamos que reposeen un lugar cálido y sin corrientes, el interior del horno previamente templado es un sitio perfecto.", 30, 30), new Pas(3, "Dividimos la masa en porciones de unos 60 gr. y le damos forma a cada uno. Estiramos cada porción con un rodillo de forma alargada", 7), new Pas(4, "Con un cuchillo hacemos unas incisiones profundas a lo largo de la masa, pero sin que lleguen a cortarla totalmente, como muestra el video. Enrollamos la pieza y la doblamos sobre si misma haciendo una caracola.", 2, "3bxmv7qRiak"), new Pas(5, "Colocamos cada porción en la bandeja del horno sobre un papel vegetal. Debemos ponerlas separadas unas de otras ya que aún crecerán bastante. Dejamos que reposen las caracolas dentro del horno aún templado, hasta que doblen su volumen.", 30, 30), new Pas(6, "Pintamos las caracolas con una pizca de mantequilla derretida, espolvoreamos con abundante azúcar y horneamos, con el horno previamente caliente a 180º C", 20, 20), new Pas(7, "Retiramos las caracolas del horno y las dejamos enfriar sobre una rejilla entes de disfrutarlas.", 10, 10))),
                new ArrayList<String>(Arrays.asList("400 gr. Harina de fuerza", "195 ml. Leche entera Central Lechera Asturiana", "80 mantequilla Central Lechera Asturiana", "1 huevo", "8 gr. Levadura fresca", "5 gr. Sal", "60 gr. Azúcar + algo para espolvorear"))));


        data.add(new Recepta("BIZCOCHO CASERO DE YOGUR",
                "Os presento uno de los bizcochos más fáciles de preparar y con un resultado de rechupete. Este bizcocho admite multitud de variaciones, lo puedes utilizar como base de distintas tartas o añadirle trocitos de frutas o frutos secos. Y por supuesto, tomarlo tal cual, como os lo presento aquí, bizcocho casero de yogur, un éxito garantizado.", 2.5, "http://www.lacocinademasito.com/recetas-recomendadas/files/styles/receta_full/public/receta/bizcocho-de-yogur.jpg",
                new ArrayList<Pas>(Arrays.asList(new Pas(1, "Añadimos el yogur a un bol grande y lavamos el potito o envase donde viene el yogur. Precalentamos el horno a 200º C y untamos el molde que vamos a utilizar con mantequilla, en la base y los lados. Espolvoreamos con un pellizco de harina y quitamos el exceso de harina. Reservamos..", 4), new Pas(2, "Batimos los huevos con unas varillas, cuando empiecen a blanquear, añadimos una pizca de sal. Medimos el azúcar y volvemos a batir, ya tenemos la base lista.", 4), new Pas(3, "Añadimos en el bol una medida de aceite de oliva suave, la levadura química y medimos de nuevo la harina con el vasito", 6), new Pas(4, "Metemos todo en el bol y batimos con unas varillas . Debe de quedar una masa homogénea y fina. Vertemos la mezcla en el molde", 6), new Pas(5, "Horneamos. Tenéis que poner el futuro bizcocho en la bandeja del medio con calor arriba y abajo, sin aire, a 180º C.", 30, 30), new Pas(6, "Dejamos que se termine de enfriar sobre una rejilla para evitar que coja humedad. Listo para comer.", 11, 11))),
                new ArrayList<String>(Arrays.asList("1 medida de yogur de aceite suave de oliva", "1 medida de yogur (en este caso natural azucarado)", "2 medidas de yogur de azúcar blanquilla", "3 medidas de yogur de harina de trigo (o de maíz)", "3 huevos tamaño mediano", "1 sobrecito de levadura química en polvo o polvo de hornear (16 g.)", "1 pizca de sal", "un poquito de mantequilla y una pizca de harina, para la base del bizcocho"))));

        data.add(new Recepta("MOUSSE DE FRESAS",
                "Cómo preparar una mousse de fresas. La receta de hoy es una de esas que podemos preparar con casi nada, y con la que conseguiremos resultados geniales. Bien sea porque no disponemos de tiempo o ganas para preparar un postre, o simplemente porque de repente nos asaltan unas ganas irrefrenables de dulce, esta mousse de fresa fácil es una opción muy a tener en cuenta..", 3, "https://www.1000recetas.com/postres/fotos%20recetas/postres/mousses/mousse.de.fresa.jpg",
                new ArrayList<Pas>(Arrays.asList(new Pas(1, "Calentamos en un cazo 250 ml. de agua. Cuando comience a hervir añadimos la gelatina de fresa y removemos hasta que se haya diluido.", 3), new Pas(2, "Retiramos del fuego y añadimos 250 ml. de agua fría. Removemos bien y reservamos hasta que se haya enfriado la mezcla. Una vez fría la guardamos en el frigo hasta que vemos que está casi cuajada.", 50, 50), new Pas(3, "Mientras se cuaja la gelatina de fresa montamos la nata la guardamos en la nevera. ", 5), new Pas(4, "Lavamos y troceamos las fresas y las trituramos con la batidora. Guardamos las fresas también en el frigo hasta el momento de utilizarlas, cuando la gelatina se haya cuajado.", 5), new Pas(5, "Con una batidora de varillas batimos la gelatina para deshacerla. Incorporamos la nata con las fresas y seguimos batiendo.", 4), new Pas(6, "Nos quedará una textura totalmente esponjosa y aireada. Servimos en las copas en que vayamos a presentar la mousse y guardamos en el frigo durante 2 horas.", 2))),
                new ArrayList<String>(Arrays.asList("1 sobre de gelatina de fresa en polvo (85 gr.)", "200 ml. de nata para montar", "250 gr. de fresas frescas", "500 ml. de agua"))));


        data.add(new Recepta("TARTA DE CUAJADA CON CHOCOLATE",
                "Cómo preparar una tarta de cuajada con chocolate. Os presento una receta de postre muy sencilla y con la que triunfaréis ya sea en una comida familiar, en una comida con amigos o en la merienda con los más peques de la casa.", 4, "http://1.bp.blogspot.com/-ZgZZ7-zqnfc/VJU9Z3daHOI/AAAAAAAAKfw/8-Y7495WFaM/s1600/marcado%2B9.jpg",
                new ArrayList<Pas>(Arrays.asList(new Pas(1, "Picamos las galletas lo más finas posible. Nosotros lo hemos hecho con una batidora de vaso pero si no tenéis se puede hacer envolviéndolas en un trapo de cocina y machacándolas con una cuchara o algo pesado; no queda tan fino pero sirve exactamente igual.", 6), new Pas(2, "Untamos la base del molde con una capa muy fina de mantequilla y derretimos el resto usando el microondas, así es más rápido.Mezclamos la mantequilla derretida con el azúcar con una varilla manual y añadimos las galletas trituradas. Mezclamos hasta que tenga el aspecto de una pasta y la repartimos sobre la base, presionando con la ayuda de una cuchara o con los dedos. La metemos a la nevera", 30, 30), new Pas(3, "Del litro de leche que vamos a utilizar separamos unos 200 ml aproximadamente. En ellos disolvemos los dos sobres de cuajada hasta que esté bien mezclado. El resto de la leche (800 ml) se echan a un cazo y se ponen a hervir con 50 g de azúcar.", 5), new Pas(4, "Troceamos el chocolate (cuanto más fino quede mejor se fundirá). Lo añadimos a la leche que tenemos en el cazo. Removemos a mano con la varilla hasta que obtenemos una crema homogénea y suave. Añadimos la cuajada diluida en leche y seguimos removiendo hasta que hierva durante 4 ó 5 minutos. No debemos dejarlo más tiempo pues si no la crema de chocolate se quemará. Retiramos del fuego y dejamos que se temple en el propio cazo.", 10), new Pas(5, "Vertemos con suavidad sobre la capa de galletas, siempre ayudados de una cuchara para que no caiga forme un agujero.", 1), new Pas(6, "Una vez listo la dejamos enfriar en un sitio fresco y por último la metemos en la nevera un mínimo de 4 horas. Un apunte; esta tarta está mucho mejor de un día para otro.", 2), new Pas(7, "Un poco antes de servirla, la sacamos de la nevera. Desmoldamos con la ayuda de un cuchillo para separar la base de galleta sin que se rompa. Esta tarta está deliciosa sola, pero también acompañada de nata o helado.", 5))),
        new ArrayList<String>(Arrays.asList("Ingredientes para la base de galletas: 240 g de galletas", "75 g de mantequilla", "1 cucharada sopera de azúcar", "Ingredientes para la crema de chocolate: 250 g de chocolate negro para fundir", "1 l. de leche entera", "2 sobres de cuajada (2 x 12 g.)", "Pepitas de chocolate para decorar"))));

        data.add(new Recepta("GALLETAS DE NATA",
                "Cómo hacer galletas de nata. Unas galletas con un sabor intenso a lácteo pero con un toque suave y delicado.", 3, "https://www.hogarmania.com/archivos/201801/6095-2-galletas-de-nata-xl-848x477x80xX.jpg",
                new ArrayList<Pas>(Arrays.asList(new Pas(1, "En un bol mezclamos la harina, la levadura y la sal. En otro bol batimos el huevo con el azúcar hasta que se forme una crema. Añadimos la nata y mezclamos bien.", 6), new Pas(2, "Incorporamos los ingredientes secos y con un tenedor comenzamos a integrar los ingredientes. Nos va a quedar una masa pegajosa y poco manejable.", 4), new Pas(3, "Formamos una bola y la dejamos en el frigo durante no menos de 1 hora. Retiramos la masa del frigo y la cortamos en 3 porciones. Enharinamos bien la superficie de trabajo.", 5), new Pas(4, "Con un rodillo estiramos la masa hasta que quede de medio cm. de grosor. Es fundamental que vayamos enharinando periódicamente la superficie de trabajo y el rodillo para que la masa no se pegue a la encimera. Ya que esta masa tiene una textura bastante pegajosa.", 6), new Pas(5, "Una vez tengamos la masa estirada con el grosor deseado cortamos las galletas con el cortante que queramos. Si no tenemos cortantes para galletas, con un vaso podríamos trabajar de la misma manera.", 5), new Pas(6, "Mientras el horno se precalienta a 180º C vamos colocando las galletas en una bandeja de horno forrada con papel sulfurizado.", 4), new Pas(7, "Horneamos las galletas", 10, 10), new Pas(8, "Retiramos las galletas para una rejilla hasta que se hayan enfriado. Seguimos el proceso hasta terminar la masa de galletas. Las tandas que sean necesarias.",2))),
                new ArrayList<String>(Arrays.asList("425 gr. harina", "1 huevo", "200 ml. de nata para montar 35% M.G.", "200 gr. azúcar blanquilla", "1 sobre de levadura química (8 gr.)", "Pizca de sal", "Papel sulfurizado"))));

    }

    public int getDataSize(){
        return data.size();
    }

    public Recepta getRecepta(int position){
        return data.get(position);
    }
}
